apiVersion: v1
kind: Service
metadata:
  name: arsenalinvincibles
  labels:
    app: arsenalinvincibles
spec:
  type: LoadBalancer
  selector:
    app: arsenalinvincibles
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
