apiVersion: apps/v1
kind: Deployment
metadata:
  name: ArsenalInvincibles
  labels:
    app: ArsenalInvicibles
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: ArsenalInvincibles
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: pscull01/ArsenalInvincibles:final
          imagePullPolicy: Always
          name: newimage
          ports:
            - containerPort: 80

apiVersion: v1
kind: Service
metadata:
  name: ArsenalInvincibles
  labels:
    app: ArsenalInvincibles
spec:
  type: LoadBalancer
  selector:
    app: ArsenalInvincibles
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
