apiVersion: apps/v1
kind: Deployment
metadata:
  name: arsenalinvincibles
  labels:
    app: arsenalinvicibles
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: arsenalinvincibles
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: arsenalinvincibles
    spec:
      containers:
        - image: pscull01/arsenalinvincibles:final
          imagePullPolicy: Always
          name: newimage
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: arsenalinvincibles
  labels:
    app: arsenalinvincibles
spec:
  type: LoadBalancer
  selector:
    app: arsenalinvincibles
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
